apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: be-app
  template:
    metadata:
      labels:
        app: be-app
    spec:
      containers:
      - name: be-app
        image: docker.io/frederickyapiter/be-app:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "54Mi"
            cpu: "100m"
        ports:
        - containerPort: 5000