apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
      labels:
        app: fe-app
    spec:
      containers:
      - name: fe-app
        image: frederickyapiter/fe-app:ba2483f6e0fd17d36d8a4d8efc7ff0d390c63b84
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND  # Nama variabel tergantung framework kamu
            value: "http://localhost:5000"
        resources:
          limits:
            cpu: "250m"
          requests:
            cpu: "100m"
        ports:
        - containerPort: 3000